### ISSUE TITLE
[fix] exceções de input não tratadas

### ISSUE THREAD

**Issue by guilfer-dev** [mauriciocoruja/simulador-financiamento#1]
Ao tentar utilizar o aplicativo sem informar um valor de amortização adicional não obtive sucesso. O erro `ValueError: could not convert string to float: ''` foi levantado.

**Comment by mauriciocoruja** [comment]
Obrigado por reportar, vou trabalhar nas correções

**Comment by mauriciocoruja** [comment]
Ajustes realizados. Obrigado pela contribuição.
